### ISSUE TITLE
[Need Help] correct calculation of farZ in transform.js 

### ISSUE THREAD

**Issue by prozessor13** [prozessor13/maplibre-gl-js#19]
currently the farZ value is calculated via:

    furthestDistance + elevation_in_pixels / cos(pitch)

but this formular do not work correct when pitching the map.

http://localhost:9966/debug/terrain.html#15.83/47.305778/11.351002/116/60

**Comment by HarelM** [comment]
Is this related to the issue you described in the steering committee meeting about the camera movement or is the camera movement a different issue?

**Comment by prozessor13** [comment]
No, this is a different issue. Sometimes the scene is clipped to early. 
e.g. the white areas in this scene: https://static.maptoolkit.net/maplibre/terrain.html#15.83/47.305778/11.351002/116/60
