### ISSUE TITLE
[Need Help] during panning, leave the camera in constant hight

### ISSUE THREAD

**Issue by prozessor13** [prozessor13/maplibre-gl-js#35]
Currently the camera is at a constant height, relatively to the altitude of the center-coordinate.

This should be changed, to that the camera is always on the same hight, relatively to the sea-level. To render the scene correct, it is necessary to recalculate the zoom-level on every map-movement.

**Comment by HarelM** [comment]
@lseelenbinder you said you might be able to help with this? or was it with #19?

**Comment by HarelM** [comment]
This gives the feeling of a 3D shooter game where your character goes up and down the mountains, this is kinda fun :-)

**Comment by lseelenbinder** [comment]
Thanks for the tag @HarelM! I wasn't sure where this code is. I'll try to get to looking through this sometime this week.

**Comment by lseelenbinder** [comment]
@prozessor13 I think what needs to be changed would be in transform.ts, right?

Generally speaking, what are your thoughts on setting the camera at some known "higher than everything" altitude and rendering from there? Does that make lower regions too small?

**Comment by prozessor13** [comment]
Hello Luke,

i checked in some lines of code with my current progress. Sadly this logic only works for non-tilted maps. In detail:

* pause camera-elevation-updates during map-dragging in handler_manager.ts
* on dragend recalculate zoom for the new center-terrain value
* all maptiles will render during dragging in the "current" zoomlevel
* on dragend, and after the new zoomlevel is calculated the maptiles will render with the new zoomlevel

Please look at the lines i checked in, i tried to document them inline.
https://github.com/prozessor13/maplibre-gl-js/commit/7895d045996107f576374cd1066ac2aa88b8bf7b

About your question. Sorry but i cannot follow your thoughts in detail, but some more details on my implementation.
In transform.ts._calc_matrices line 862, after all matrixes are created i translate the projMatrix by -elevation.

    mat4.translate(m, m, [0, 0, -elevation]); // elevate camera over terrain

maybe this is a bad hack, i dont know. If yes, this line of code is may the reason for all the following problems. Also this logic do not avoid diving into terrain in some cornercases, but in generally it does its job fine.

Regards. Max.

**Comment by lseelenbinder** [comment]
Hi Max,

Thanks for the detailed explanations! I now understand why you're doing it how you're doing it…

Let me try to explain.

A few facts:

1) We have the interval [0..1] in which to render elevations (assuming normalized world coordinates; obviously this changes as soon as we start tilting the map, etc.).
2) We know pretty precisely the lowest and highest points we'd ever want to render. (The lowest elevation in the world and highest elevation. Let's say -500m to 9000m.)

- One way to "solve" this is to set the coordinates 0..1 to scale from -500m to 10000m, and we set the camera to a fixed 9500m elevation (so roughly 0.95). It's a bit shortsighted, but might be good enough to work for now.
- Another option is to scale the elevation based on the highest and lowest measured values in the scene (dynamic elevation with fixed camera perspective).
- Another option would be to use a fixed elevation per zoom (each zoom has a known meters-per-pixel level), so perhaps we can take that value as the camera elevation, and adjust for high scenes in high zoom levels (e.g., Mt. Everest in z20).

Honestly, this isn't quite the problem I thought it was from the call, so I'm not sure the best way to solve it. 😄 

Happy to keep brainstorming on the thread!

**Comment by prozessor13** [comment]
Hallo Luke,

sorry for the late reply, but i currently working on other things.
Maplibre uses the last approach you described. E.g. the projMatrix Z-direction is scaled in meters.
And i have to figure out how to calculate to the zoomlevel in tilted maps in respect to:
* terrain height at the center-coordinate
* terrain latitude at the center-coordinate (maybe this is irrelevant)
* camera height of current zoomlevel
* camera elevation offset from the last center-altitude
* camera tilt angle

Except the tilt angle i have all computations done. But because of no time, i will work on this issue again next year.

Regards. Max.

**Comment by HarelM** [comment]
@prozessor13 this should be kept open, right?

**Comment by prozessor13** [comment]
Hello, this issue can be closed!

**Comment by HarelM** [comment]
I didn't notice that this issue is on the fork and not the original repo, silly me :-)
