### ISSUE TITLE
Label (clustering?) not working correctly

### ISSUE THREAD

**Issue by acalcutt** [prozessor13/maplibre-gl-js#38]
I am having an issue in the terrain3d branch where point label distribution does not seem to be working correctly. 

This is my example with the terrain3d branch
https://stackblitz.com/edit/web-platform-wxkjfp?file=index.html
![points_terrain3d](https://user-images.githubusercontent.com/3792408/143533703-e7623b72-cbc9-4a9b-a5be-eb41cbc7dcad.png)

In this example, all the black circles should have a label, but you can see they are missing around the outer edge. If you move the screen around, the lables continue to stay in the center and out edge stays missing. Also, If you zoom in, you would expect more labels to be visible, but instead there are even less labels. 

I have also tested this with the maplibre master branch (2.0.0 pre6) here
https://stackblitz.com/edit/web-platform-ddhwtr?file=index.html
![points_2 0 0-pre6](https://user-images.githubusercontent.com/3792408/143534065-ed8b8f91-6a70-429b-9b93-368694928943.png)

In this second example, you can see the label distribution is more what you would expect. there is no missing border of labels and when you zoom in more labels can be seen

**Comment by prozessor13** [comment]
Thx for the well prepared bugreport :) I have fixed the issue!
